baseURL = 'https://Project163.github.io/'
languageCode = 'zh-cn'
title = 'Blog'
theme = 'PaperMod'

[params]
    defaultTheme = "auto"
    ShowReadingTime = true
    ShowShareButtons = true

[outputs]
    home = ["HTML", "RSS", "JSON"]
